openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is Contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-3-2lfu.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/requestResetPassword.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/resetPwd.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
